# Generated by Django 5.0.7 on 2024-10-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=20)),
                ('userphonenum', models.CharField(max_length=15)),
                ('useremail', models.EmailField(max_length=254)),
            ],
        ),
    ]
