# Generated by Django 5.0.7 on 2024-10-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('eventID', models.AutoField(primary_key=True, serialize=False)),
                ('eventname', models.CharField(max_length=100)),
                ('eventlocation', models.CharField(max_length=100)),
                ('eventprice', models.FloatField()),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
            ],
        ),
    ]
