# Generated by Django 5.0.7 on 2024-10-08 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('registerID', models.AutoField(primary_key=True, serialize=False)),
                ('numofticket', models.IntegerField()),
                ('registerdate', models.DateField()),
                ('paymentmethod', models.CharField(max_length=20)),
                ('totalprice', models.IntegerField()),
                ('registerstatus', models.CharField(max_length=15)),
                ('eventID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.event')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.user')),
            ],
        ),
    ]
