# Generated by Django 5.0.7 on 2024-10-08 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('reviewID', models.AutoField(primary_key=True, serialize=False)),
                ('reviewcomment', models.CharField(max_length=1000)),
                ('eventID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.event')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.user')),
            ],
        ),
    ]
