# Generated by Django 5.0.7 on 2024-10-15 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('newsletterID', models.AutoField(primary_key=True, serialize=False)),
                ('newsletteremail', models.EmailField(max_length=254)),
            ],
        ),
    ]
