# Generated by Django 5.0.7 on 2024-10-15 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_newsletter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newsletter',
        ),
    ]
