# Generated by Django 5.0.7 on 2024-10-18 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_delete_newsletter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
